name: ci

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  native:
    name: native
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: native
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Test
        run: cargo test

      - name: Release cdylib
        run: cargo build --release
